"""Bazalt — Python library for rapid GPU shader prototyping using Vulkan."""

from bazalt._core import *  # noqa: F401, F403
from bazalt._core import (  # noqa: F401 — explicit re-exports for IDE visibility
    Context,
    RenderTarget,
    RenderTargetBase,
    SwapchainRenderer,
    Window,
    Device,
    list_devices,
    poll_events,
    Logger,
    LogMessage,
    Buffer,
    ShaderModule,
    Image,
    Sampler,
    Pipeline,
    GraphicsPipelineBuilder,
    ComputePipelineBuilder,
    DescriptorPool,
    DescriptorSet,
    CommandBuffer,
    RenderingScope,
    Timer,
    LabelScope,
    OcclusionQuery,
    MemoryStats,
    MouseState,
    WindowMode,
    BufferType,
    DataType,
    ShaderStage,
    VertexFormat,
    Topology,
    Access,
    Format,
    Filter,
    AddressMode,
    CompareOp,
    PresentMode,
    CullMode,
    FrontFace,
    PolygonMode,
    BlendMode,
    StencilOp,
    BorderColor,
    MemoryUsage,
    Severity,
    Source,
    Feature,
    BazaltError,
    InitializationError,
    DeviceLostError,
    OutOfMemoryError,
    ShaderError,
    WindowError,
    ResourceError,
)

__version__ = "0.18.0"

__all__ = [
    # Core
    "Context",
    "RenderTarget",
    "RenderTargetBase",
    "SwapchainRenderer",
    "Window",
    "Device",
    "list_devices",
    "poll_events",
    "Logger",
    "LogMessage",
    # Resources
    "Buffer",
    "ShaderModule",
    "Image",
    "Sampler",
    "Pipeline",
    "GraphicsPipelineBuilder",
    "ComputePipelineBuilder",
    "DescriptorPool",
    "DescriptorSet",
    "CommandBuffer",
    "RenderingScope",
    "Timer",
    "LabelScope",
    "OcclusionQuery",
    # Data types
    "MemoryStats",
    "MouseState",
    "WindowMode",
    "BufferType",
    "DataType",
    "ShaderStage",
    "VertexFormat",
    "Topology",
    "Access",
    "Format",
    "Filter",
    "AddressMode",
    "CompareOp",
    "PresentMode",
    "CullMode",
    "FrontFace",
    "PolygonMode",
    "BlendMode",
    "StencilOp",
    "BorderColor",
    "MemoryUsage",
    "Severity",
    "Source",
    "Feature",
    # Errors — the type is the recoverability contract
    "BazaltError",
    "InitializationError",
    "DeviceLostError",
    "OutOfMemoryError",
    "ShaderError",
    "WindowError",
    "ResourceError",
    # Version
    "__version__",
]
